name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/wlodek_profile.jpg

  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts\Josefin_Sans\static\JosefinSans-LightItalic.ttf
          weight: 200
          style: italic

        - asset: fonts\Josefin_Sans\static/JosefinSans-Regular.ttf
          weight: 400
        - asset: fonts\Josefin_Sans\static/JosefinSans-Italic.ttf
          weight: 400
          style: italic

        - asset: fonts\Josefin_Sans\static/JosefinSans-Medium.ttf
          weight: 500

        - asset: fonts\Josefin_Sans\static/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: fonts\Josefin_Sans\static/JosefinSans-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: fonts\Josefin_Sans\static/JosefinSans-Bold.ttf
          weight: 700
        - asset: fonts\Josefin_Sans\static/JosefinSans-BoldItalic.ttf
          weight: 700
          style: italic

        

        
